---
#   Copyright 2016 Rezart Qelibari
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Collect information about users and groups on macOS systems.

- name: "Get list of all users (excluding osx internals)."
  shell: "dscl . list /Users | grep -v '^_.*\\|^daemon\\|^nobody'"
  register: r_userslist
  changed_when: false
  check_mode: no
  tags:
    - macos_all_users

- name: "Get user home folders."
  shell: "dscl . -read /Users/{{user}} NFSHomeDirectory | cut -d' ' -f2"
  with_items: "{{ r_userslist.stdout_lines }}"
  register: r_userhomes
  changed_when: false
  loop_control:
    label: "{{user}}"
    loop_var: user
  check_mode: no
  tags:
    - macos_all_users_home

- set_fact:
    f_userslist: "{{r_userslist.stdout_lines}}"
    f_usershome: "{{r_userhomes.results}}"