---
###############################################################################
# appmanager user                                                             #
###############################################################################
appmanager:
  name: lappadmin  #local app admin
  group: appmanager